spring:
  application:
    name: spring-openai-demo

  ai:
   openai:
     api-key: ${OPENAI_API_KEY}

#     chat:
#       options:
#         model: gpt-4o-mini
#         temperature: 0.3
#         max-tokens: 10

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG


server:
  port: 9293